CREATE VIEW dim_player_stint AS 
	SELECT 
		dim_player_stint_sq1."Player_Stint_ID", 
		dim_player_stint_sq1."Player_ID", 
		dim_player_stint_sq1."Player_Name", 
		dim_player_stint_sq1."Coach_Stint_ID", 
		dim_player_stint_sq1."Coach_ID", 
		dim_player_stint_sq1."Coach_Name", 
		dim_player_stint_sq1."Franchise_ID",
		dim_player_stint_sq1."Franchise_Name",
		dim_player_stint_sq1."Primary_Position",
		MIN(offense."Age") AS "Start_Age",
		MAX(offense."Age") AS "End_Age",
		MIN(offense."Games") AS "Min_Games_in_Season",
		MIN(COALESCE(NULLIF(offense."Starts", ''), 0)) AS "Min_Starts_in_Season",
		MIN(COALESCE(NULLIF(offense."Pass_Completions", ''), 0)) AS "Min_Pass_Completions_in_Season",
		MIN(COALESCE(NULLIF(offense."Pass_Attempts", ''), 0)) AS "Min_Pass_Attempts_in_Season",
		MIN(COALESCE(NULLIF(offense."Pass_Yards", ''), 0)) AS "Min_Pass_Yards_in_Season",
		MIN(COALESCE(NULLIF(offense."Pass_TDs", ''), 0)) AS "Min_Pass_TDs_in_Season",
		MIN(COALESCE(NULLIF(offense."Interceptions", ''), 0)) AS "Min_Interceptions_in_Season",
		MIN(COALESCE(NULLIF(offense."Rush_Attempts", ''), 0)) AS "Min_Rush_Attempts_in_Season",
		MIN(COALESCE(NULLIF(offense."Rush_Yards", ''), 0)) AS "Min_Rush_Yards_in_Season",
		MIN(COALESCE(NULLIF(offense."Yards_Per_Rush", ''), 0)) AS "Min_Yards_Per_Rush_in_Season",
		MIN(COALESCE(NULLIF(offense."Rush_TDs", ''), 0)) AS "Min_Rush_TDs_in_Season",
		MIN(COALESCE(NULLIF(offense."Targets", ''), 0)) AS "Min_Targets_in_Season",
		MIN(COALESCE(NULLIF(offense."Receptions", ''), 0)) AS "Min_Receptions_in_Season",
		MIN(COALESCE(NULLIF(offense."Receive_Yards", ''), 0)) AS "Min_Receive_Yards_in_Season",
		MIN(COALESCE(NULLIF(offense."Yards_Per_Reception", ''), 0)) AS "Min_Yards_Per_Reception_in_Season",
		MIN(COALESCE(NULLIF(offense."Receive_TDs", ''), 0)) AS "Min_Receive_TDs_in_Season",
		MIN(COALESCE(NULLIF(offense."Fumbles", ''), 0)) AS "Min_Fumbles_in_Season",
		MIN(COALESCE(NULLIF(offense."Fumbles_Lost", ''), 0)) AS "Min_Fumbles_Lost_in_Season",
		MIN(COALESCE(NULLIF(offense."Total_TDs", ''), 0)) AS "Min_Total_TDs_in_Season",
		MIN(COALESCE(NULLIF(offense."Rush_Conversions", ''), 0)) AS "Min_Rush_Conversions_in_Season",
		MIN(COALESCE(NULLIF(offense."Pass_Conversions", ''), 0)) AS "Min_Pass_Conversions_in_Season",
		0 AS "Min_0-19_Attempts_in_Season",
		0 AS "Min_0-19_Makes_in_Season",
		0 AS "Min_20-29_Attempts_in_Season",
		0 AS "Min_20-29_Makes_in_Season",
		0 AS "Min_30-39_Attempts_in_Season",
		0 AS "Min_30-39_Makes_in_Season",
		0 AS "Min_40-49_Attempts_in_Season",
		0 AS "Min_40-49_Makes_in_Season",
		0 AS "Min_50+_Attempts_in_Season",
		0 AS "Min_50+_Makes_in_Season",
		0 AS "Min_FG_Attempts_in_Season",
		0 AS "Min_FG_Makes_in_Season",
		0 AS "Min_Longest_Make_in_Season",
		0 AS "Min_FG_Percent_in_Season",
		0 AS "Min_XP_Attempts_in_Season",
		0 AS "Min_XP_Makes_in_Season",
		0 AS "Min_XP_Percent_in_Season",
		0 AS "Min_Kickoffs_in_Season",
		0 AS "Min_Kickoff_Yards_in_Season",
		0 AS "Min_Touchbacks_in_Season",
		0 AS "Min_Touchback_Percent_in_Season",
		0 AS "Min_Kickoff_Average_in_Season",
		0 AS "Min_Punts_in_Season",
		0 AS "Min_Punt_Yards_in_Season",
		0 AS "Min_Longest_Punt_in_Season",
		0 AS "Min_Punts_Blocked_in_Season",
		0 AS "Min_Yards_Per_Punt_in_Season",
		MIN(COALESCE(NULLIF(offense."Standard_Points", ''), 0)) AS "Min_Standard_Points_in_Season",
		MIN(COALESCE(NULLIF(offense."PPR_Points", ''), 0)) AS "Min_PPR_Points_in_Season",
		MIN(COALESCE(NULLIF(offense."DraftKings_Points", ''), 0)) AS "Min_DraftKings_Points_in_Season",
		MIN(COALESCE(NULLIF(offense."FanDuel_Points", ''), 0)) AS "Min_FanDuel_Points_in_Season",
		MIN(COALESCE(NULLIF(offense."VBD", ''), 0)) AS "Min_VBD_in_Season",
		MIN(COALESCE(NULLIF(offense."Position_Rank", ''), 0)) AS "Min_Position_Rank_in_Season",
		MIN(COALESCE(NULLIF(offense."Overall_Rank", ''), 0)) AS "Min_Overall_Rank_in_Season",
		MAX(COALESCE(NULLIF(offense."Games", ''), 0)) AS "Max_Games_in_Season",
		MAX(COALESCE(NULLIF(offense."Starts", ''), 0)) AS "Max_Starts_in_Season",
		MAX(COALESCE(NULLIF(offense."Pass_Completions", ''), 0)) AS "Max_Pass_Completions_in_Season",
		MAX(COALESCE(NULLIF(offense."Pass_Attempts", ''), 0)) AS "Max_Pass_Attempts_in_Season",
		MAX(COALESCE(NULLIF(offense."Pass_Yards", ''), 0)) AS "Max_Pass_Yards_in_Season",
		MAX(COALESCE(NULLIF(offense."Pass_TDs", ''), 0)) AS "Max_Pass_TDs_in_Season",
		MAX(COALESCE(NULLIF(offense."Interceptions", ''), 0)) AS "Max_Interceptions_in_Season",
		MAX(COALESCE(NULLIF(offense."Rush_Attempts", ''), 0)) AS "Max_Rush_Attempts_in_Season",
		MAX(COALESCE(NULLIF(offense."Rush_Yards", ''), 0)) AS "Max_Rush_Yards_in_Season",
		MAX(COALESCE(NULLIF(offense."Yards_Per_Rush", ''), 0)) AS "Max_Yards_Per_Rush_in_Season",
		MAX(COALESCE(NULLIF(offense."Rush_TDs", ''), 0)) AS "Max_Rush_TDs_in_Season",
		MAX(COALESCE(NULLIF(offense."Targets", ''), 0)) AS "Max_Targets_in_Season",
		MAX(COALESCE(NULLIF(offense."Receptions", ''), 0)) AS "Max_Receptions_in_Season",
		MAX(COALESCE(NULLIF(offense."Receive_Yards", ''), 0)) AS "Max_Receive_Yards_in_Season",
		MAX(COALESCE(NULLIF(offense."Yards_Per_Reception", ''), 0)) AS "Max_Yards_Per_Reception_in_Season",
		MAX(COALESCE(NULLIF(offense."Receive_TDs", ''), 0)) AS "Max_Receive_TDs_in_Season",
		MAX(COALESCE(NULLIF(offense."Fumbles", ''), 0)) AS "Max_Fumbles_in_Season",
		MAX(COALESCE(NULLIF(offense."Fumbles_Lost", ''), 0)) AS "Max_Fumbles_Lost_in_Season",
		MAX(COALESCE(NULLIF(offense."Total_TDs", ''), 0)) AS "Max_Total_TDs_in_Season",
		MAX(COALESCE(NULLIF(offense."Rush_Conversions", ''), 0)) AS "Max_Rush_Conversions_in_Season",
		MAX(COALESCE(NULLIF(offense."Pass_Conversions", ''), 0)) AS "Max_Pass_Conversions_in_Season",
		0 AS "Max_0-19_Attempts_in_Season",
		0 AS "Max_0-19_Makes_in_Season",
		0 AS "Max_20-29_Attempts_in_Season",
		0 AS "Max_20-29_Makes_in_Season",
		0 AS "Max_30-39_Attempts_in_Season",
		0 AS "Max_30-39_Makes_in_Season",
		0 AS "Max_40-49_Attempts_in_Season",
		0 AS "Max_40-49_Makes_in_Season",
		0 AS "Max_50+_Attempts_in_Season",
		0 AS "Max_50+_Makes_in_Season",
		0 AS "Max_FG_Attempts_in_Season",
		0 AS "Max_FG_Makes_in_Season",
		0 AS "Max_Longest_Make_in_Season",
		0 AS "Max_FG_Percent_in_Season",
		0 AS "Max_XP_Attempts_in_Season",
		0 AS "Max_XP_Makes_in_Season",
		0 AS "Max_XP_Percent_in_Season",
		0 AS "Max_Kickoffs_in_Season",
		0 AS "Max_Kickoff_Yards_in_Season",
		0 AS "Max_Touchbacks_in_Season",
		0 AS "Max_Touchback_Percent_in_Season",
		0 AS "Max_Kickoff_Average_in_Season",
		0 AS "Max_Punts_in_Season",
		0 AS "Max_Punt_Yards_in_Season",
		0 AS "Max_Longest_Punt_in_Season",
		0 AS "Max_Punts_Blocked_in_Season",
		0 AS "Max_Yards_Per_Punt_in_Season",
		MAX(COALESCE(NULLIF(offense."Standard_Points", ''), 0)) AS "Max_Standard_Points_in_Season",
		MAX(COALESCE(NULLIF(offense."PPR_Points", ''), 0)) AS "Max_PPR_Points_in_Season",
		MAX(COALESCE(NULLIF(offense."DraftKings_Points", ''), 0)) AS "Max_DraftKings_Points_in_Season",
		MAX(COALESCE(NULLIF(offense."FanDuel_Points", ''), 0)) AS "Max_FanDuel_Points_in_Season",
		MAX(COALESCE(NULLIF(offense."VBD", ''), 0)) AS "Max_VBD_in_Season",
		MAX(COALESCE(NULLIF(offense."Position_Rank", ''), 0)) AS "Max_Position_Rank_in_Season",
		MAX(COALESCE(NULLIF(offense."Overall_Rank", ''), 0)) AS "Max_Overall_Rank_in_Season",
		SUM(COALESCE(NULLIF(offense."Games", ''), 0)) AS "Total_Games",
		SUM(COALESCE(NULLIF(offense."Starts", ''), 0)) AS "Total_Starts",
		SUM(COALESCE(NULLIF(offense."Pass_Completions", ''), 0)) AS "Total_Pass_Completions",
		SUM(COALESCE(NULLIF(offense."Pass_Attempts", ''), 0)) AS "Total_Pass_Attempts",
		SUM(COALESCE(NULLIF(offense."Pass_Yards", ''), 0)) AS "Total_Pass_Yards",
		SUM(COALESCE(NULLIF(offense."Pass_TDs", ''), 0)) AS "Total_Pass_TDs",
		SUM(COALESCE(NULLIF(offense."Interceptions", ''), 0)) AS "Total_Interceptions",
		SUM(COALESCE(NULLIF(offense."Rush_Attempts", ''), 0)) AS "Total_Rush_Attempts",
		SUM(COALESCE(NULLIF(offense."Rush_Yards", ''), 0)) AS "Total_Rush_Yards",
		SUM(COALESCE(NULLIF(offense."Yards_Per_Rush", ''), 0)) AS "Total_Yards_Per_Rush",
		SUM(COALESCE(NULLIF(offense."Rush_TDs", ''), 0)) AS "Total_Rush_TDs",
		SUM(COALESCE(NULLIF(offense."Targets", ''), 0)) AS "Total_Targets",
		SUM(COALESCE(NULLIF(offense."Receptions", ''), 0)) AS "Total_Receptions",
		SUM(COALESCE(NULLIF(offense."Receive_Yards", ''), 0)) AS "Total_Receive_Yards",
		SUM(COALESCE(NULLIF(offense."Yards_Per_Reception", ''), 0)) AS "Total_Yards_Per_Reception",
		SUM(COALESCE(NULLIF(offense."Receive_TDs", ''), 0)) AS "Total_Receive_TDs",
		SUM(COALESCE(NULLIF(offense."Fumbles", ''), 0)) AS "Total_Fumbles",
		SUM(COALESCE(NULLIF(offense."Fumbles_Lost", ''), 0)) AS "Total_Fumbles_Lost",
		SUM(COALESCE(NULLIF(offense."Total_TDs", ''), 0)) AS "Total_TDs",
		SUM(COALESCE(NULLIF(offense."Rush_Conversions", ''), 0)) AS "Total_Rush_Conversions",
		SUM(COALESCE(NULLIF(offense."Pass_Conversions", ''), 0)) AS "Total_Pass_Conversions",
		0 AS "Total_0-19_Attempts",
		0 AS "Total_0-19_Makes",
		0 AS "Total_20-29_Attempts",
		0 AS "Total_20-29_Makes",
		0 AS "Total_30-39_Attempts",
		0 AS "Total_30-39_Makes",
		0 AS "Total_40-49_Attempts",
		0 AS "Total_40-49_Makes",
		0 AS "Total_50+_Attempts",
		0 AS "Total_50+_Makes",
		0 AS "Total_FG_Attempts",
		0 AS "Total_FG_Makes",
		0 AS "Total_Longest_Make",
		0 AS "Total_FG_Percent",
		0 AS "Total_XP_Attempts",
		0 AS "Total_XP_Makes",
		0 AS "Total_XP_Percent",
		0 AS "Total_Kickoffs",
		0 AS "Total_Kickoff_Yards",
		0 AS "Total_Touchbacks",
		0 AS "Total_Touchback_Percent",
		0 AS "Total_Kickoff_Average",
		0 AS "Total_Punts",
		0 AS "Total_Punt_Yards",
		0 AS "Total_Longest_Punt",
		0 AS "Total_Punts_Blocked",
		0 AS "Total_Yards_Per_Punt",
		SUM(COALESCE(NULLIF(offense."Standard_Points", ''), 0)) AS "Total_Standard_Points",
		SUM(COALESCE(NULLIF(offense."PPR_Points", ''), 0)) AS "Total_PPR_Points",
		SUM(COALESCE(NULLIF(offense."DraftKings_Points", ''), 0)) AS "Total_DraftKings_Points",
		SUM(COALESCE(NULLIF(offense."FanDuel_Points", ''), 0)) AS "Total_FanDuel_Points",
		SUM(COALESCE(NULLIF(offense."VBD", ''), 0)) AS "Total_VBD"
	FROM (
		SELECT 
			offense."Player", 
			offense."Year",
			offense."Team",
			id_player."Player_Stint_ID", 
			id_player."Player_ID", 
			id_player."Player_Name", 
			dim_team."Coach_Stint_ID", 
			dim_team."Coach_ID", 
			dim_team."Coach_Name", 
			dim_team."Franchise_ID",
			dim_team."Franchise_Name",
			lkp_pos_stint."Primary_Position"
		FROM offense 
		LEFT JOIN lkp_franchise_abbreviation AS lkp_abrv 
			ON offense."Team" = lkp_abrv."Abbreviation" 
		LEFT JOIN dim_team 
			ON lkp_abrv."Franchise_Name" = dim_team."Franchise_Name" 
			AND offense."Year" = dim_team."Year" 
		INNER JOIN lkp_player_name AS lkp_name 
			ON offense."Player" = lkp_name."Player_Lookup_Name" 
		LEFT JOIN id_player 
			ON lkp_name."Player_Name" = id_player."Player_Name" 
			AND dim_team."Franchise_ID" = id_player."Franchise_ID" 
		LEFT JOIN lkp_primary_position_stint AS lkp_pos_stint 
			ON id_player."Player_Stint_ID" = lkp_pos_stint."Player_Stint_ID"
		GROUP BY
			offense."Player", 
			offense."Year",
			offense."Team",
			id_player."Player_Stint_ID", 
			id_player."Player_ID", 
			id_player."Player_Name", 
			dim_team."Coach_Stint_ID", 
			dim_team."Coach_ID", 
			dim_team."Coach_Name", 
			dim_team."Franchise_ID",
			dim_team."Franchise_Name",
			lkp_pos_stint."Primary_Position") AS dim_player_stint_sq1
	INNER JOIN offense 
		ON dim_player_stint_sq1."Player" = offense."Player" 
		AND dim_player_stint_sq1."Year" = offense."Year" 
		AND dim_player_stint_sq1."Team" = offense."Team" 
	WHERE dim_player_stint_sq1."Player_Stint_ID" IS NOT NULL
	GROUP BY 
		dim_player_stint_sq1."Player_Stint_ID", 
		dim_player_stint_sq1."Player_ID", 
		dim_player_stint_sq1."Player_Name", 
		dim_player_stint_sq1."Franchise_ID",
		dim_player_stint_sq1."Franchise_Name",
		dim_player_stint_sq1."Primary_Position"
	UNION ALL 
	SELECT
		dim_player_stint_sq2."Player_Stint_ID", 
		dim_player_stint_sq2."Player_ID", 
		dim_player_stint_sq2."Player_Name", 
		dim_player_stint_sq2."Coach_Stint_ID", 
		dim_player_stint_sq2."Coach_ID", 
		dim_player_stint_sq2."Coach_Name", 
		dim_player_stint_sq2."Franchise_ID",
		dim_player_stint_sq2."Franchise_Name",
		dim_player_stint_sq2."Primary_Position",
		MIN(kicking."Age") AS "Start_Age",
		MAX(kicking."Age") AS "End_Age",
		MIN(kicking."Games") AS "Min_Games",
		MIN(COALESCE(NULLIF(kicking."Starts", ''), 0)) AS "Min_Starts",
		0 AS "Min_Pass_Completions_in_Season",
		0 AS "Min_Pass_Attempts_in_Season",
		0 AS "Min_Pass_Yards_in_Season",
		0 AS "Min_Pass_TDs_in_Season",
		0 AS "Min_Interceptions_in_Season",
		0 AS "Min_Rush_Attempts_in_Season",
		0 AS "Min_Rush_Yards_in_Season",
		0 AS "Min_Yards_Per_Rush_in_Season",
		0 AS "Min_Rush_TDs_in_Season",
		0 AS "Min_Targets_in_Season",
		0 AS "Min_Receptions_in_Season",
		0 AS "Min_Receive_Yards_in_Season",
		0 AS "Min_Yards_Per_Reception_in_Season",
		0 AS "Min_Receive_TDs_in_Season",
		0 AS "Min_Fumbles_in_Season",
		0 AS "Min_Fumbles_Lost_in_Season",
		0 AS "Min_Total_TDs_in_Season",
		0 AS "Min_Rush_Conversions_in_Season",
		0 AS "Min_Pass_Conversions_in_Season",
		MIN(COALESCE(NULLIF(kicking."0-19_Attempts", ''), 0)) AS "Min_0-19_Attempts_in_Season",
		MIN(COALESCE(NULLIF(kicking."0-19_Makes", ''), 0)) AS "Min_0-19_Makes_in_Season",
		MIN(COALESCE(NULLIF(kicking."20-29_Attempts", ''), 0)) AS "Min_20-29_Attempts_in_Season",
		MIN(COALESCE(NULLIF(kicking."20-29_Makes", ''), 0)) AS "Min_20-29_Makes_in_Season",
		MIN(COALESCE(NULLIF(kicking."30-39_Attempts", ''), 0)) AS "Min_30-39_Attempts_in_Season",
		MIN(COALESCE(NULLIF(kicking."30-39_Makes", ''), 0)) AS "Min_30-39_Makes_in_Season",
		MIN(COALESCE(NULLIF(kicking."40-49_Attempts", ''), 0)) AS "Min_40-49_Attempts_in_Season",
		MIN(COALESCE(NULLIF(kicking."40-49_Makes", ''), 0)) AS "Min_40-49_Makes_in_Season",
		MIN(COALESCE(NULLIF(kicking."50+_Attempts", ''), 0)) AS "Min_50+_Attempts_in_Season",
		MIN(COALESCE(NULLIF(kicking."50+_Makes", ''), 0)) AS "Min_50+_Makes_in_Season",
		MIN(COALESCE(NULLIF(kicking."FG_Attempts", ''), 0)) AS "Min_FG_Attempts_in_Season",
		MIN(COALESCE(NULLIF(kicking."FG_Makes", ''), 0)) AS "Min_FG_Makes_in_Season",
		MIN(COALESCE(NULLIF(kicking."Longest_Make", ''), 0)) AS "Min_Longest_Make_in_Season",
		MIN(COALESCE(NULLIF(kicking."FG_Percent", ''), 0)) AS "Min_FG_Percent_in_Season",
		MIN(COALESCE(NULLIF(kicking."XP_Attempts", ''), 0)) AS "Min_XP_Attempts_in_Season",
		MIN(COALESCE(NULLIF(kicking."XP_Makes", ''), 0)) AS "Min_XP_Makes_in_Season",
		MIN(COALESCE(NULLIF(kicking."XP_Percent", ''), 0)) AS "Min_XP_Percent_in_Season",
		MIN(COALESCE(NULLIF(kicking."Kickoffs", ''), 0)) AS "Min_Kickoffs_in_Season",
		MIN(COALESCE(NULLIF(kicking."Kickoff_Yards", ''), 0)) AS "Min_Kickoff_Yards_in_Season",
		MIN(COALESCE(NULLIF(kicking."Touchbacks", ''), 0)) AS "Min_Touchbacks_in_Season",
		MIN(COALESCE(NULLIF(kicking."Touchback_Percent", ''), 0)) AS "Min_Touchback_Percent_in_Season",
		MIN(COALESCE(NULLIF(kicking."Kickoff_Average", ''), 0)) AS "Min_Kickoff_Average_in_Season",
		MIN(COALESCE(NULLIF(kicking."Punts", ''), 0)) AS "Min_Punts_in_Season",
		MIN(COALESCE(NULLIF(kicking."Punt_Yards", ''), 0)) AS "Min_Punt_Yards_in_Season",
		MIN(COALESCE(NULLIF(kicking."Longest_Punt", ''), 0)) AS "Min_Longest_Punt_in_Season",
		MIN(COALESCE(NULLIF(kicking."Punts_Blocked", ''), 0)) AS "Min_Punts_Blocked_in_Season",
		MIN(COALESCE(NULLIF(kicking."Yards_Per_Punt", ''), 0)) AS "Min_Yards_Per_Punt_in_Season",
		0 AS "Min_Standard_Points_in_Season",
		0 AS "Min_PPR_Points_in_Season",
		0 AS "Min_DraftKings_Points_in_Season",
		0 AS "Min_FanDuel_Points_in_Season",
		0 AS "Min_VBD_in_Season",
		MIN(COALESCE(NULLIF(kicking."Rank", ''), 0)) AS "Min_Position_Rank_in_Season",
		MIN(COALESCE(NULLIF(kicking."Rank", ''), 0)) AS "Min_Overall_Rank_in_Season",
		MAX(COALESCE(NULLIF(kicking."Games", ''), 0)) AS "Max_Games_in_Season",
		MAX(COALESCE(NULLIF(kicking."Starts", ''), 0)) AS "Max_Starts_in_Season",
		0 AS "Max_Pass_Completions_in_Season",
		0 AS "Max_Pass_Attempts_in_Season",
		0 AS "Max_Pass_Yards_in_Season",
		0 AS "Max_Pass_TDs_in_Season",
		0 AS "Max_Interceptions_in_Season",
		0 AS "Max_Rush_Attempts_in_Season",
		0 AS "Max_Rush_Yards_in_Season",
		0 AS "Max_Yards_Per_Rush_in_Season",
		0 AS "Max_Rush_TDs_in_Season",
		0 AS "Max_Targets_in_Season",
		0 AS "Max_Receptions_in_Season",
		0 AS "Max_Receive_Yards_in_Season",
		0 AS "Max_Yards_Per_Reception_in_Season",
		0 AS "Max_Receive_TDs_in_Season",
		0 AS "Max_Fumbles_in_Season",
		0 AS "Max_Fumbles_Lost_in_Season",
		0 AS "Max_Total_TDs_in_Season",
		0 AS "Max_Rush_Conversions_in_Season",
		0 AS "Max_Pass_Conversions_in_Season",
		MAX(COALESCE(NULLIF(kicking."0-19_Attempts", ''), 0)) AS "Max_0-19_Attempts_in_Season",
		MAX(COALESCE(NULLIF(kicking."0-19_Makes", ''), 0)) AS "Max_0-19_Makes_in_Season",
		MAX(COALESCE(NULLIF(kicking."20-29_Attempts", ''), 0)) AS "Max_20-29_Attempts_in_Season",
		MAX(COALESCE(NULLIF(kicking."20-29_Makes", ''), 0)) AS "Max_20-29_Makes_in_Season",
		MAX(COALESCE(NULLIF(kicking."30-39_Attempts", ''), 0)) AS "Max_30-39_Attempts_in_Season",
		MAX(COALESCE(NULLIF(kicking."30-39_Makes", ''), 0)) AS "Max_30-39_Makes_in_Season",
		MAX(COALESCE(NULLIF(kicking."40-49_Attempts", ''), 0)) AS "Max_40-49_Attempts_in_Season",
		MAX(COALESCE(NULLIF(kicking."40-49_Makes", ''), 0)) AS "Max_40-49_Makes_in_Season",
		MAX(COALESCE(NULLIF(kicking."50+_Attempts", ''), 0)) AS "Max_50+_Attempts_in_Season",
		MAX(COALESCE(NULLIF(kicking."50+_Makes", ''), 0)) AS "Max_50+_Makes_in_Season",
		MAX(COALESCE(NULLIF(kicking."FG_Attempts", ''), 0)) AS "Max_FG_Attempts_in_Season",
		MAX(COALESCE(NULLIF(kicking."FG_Makes", ''), 0)) AS "Max_FG_Makes_in_Season",
		MAX(COALESCE(NULLIF(kicking."Longest_Make", ''), 0)) AS "Max_Longest_Make_in_Season",
		MAX(COALESCE(NULLIF(kicking."FG_Percent", ''), 0)) AS "Max_FG_Percent_in_Season",
		MAX(COALESCE(NULLIF(kicking."XP_Attempts", ''), 0)) AS "Max_XP_Attempts_in_Season",
		MAX(COALESCE(NULLIF(kicking."XP_Makes", ''), 0)) AS "Max_XP_Makes_in_Season",
		MAX(COALESCE(NULLIF(kicking."XP_Percent", ''), 0)) AS "Max_XP_Percent_in_Season",
		MAX(COALESCE(NULLIF(kicking."Kickoffs", ''), 0)) AS "Max_Kickoffs_in_Season",
		MAX(COALESCE(NULLIF(kicking."Kickoff_Yards", ''), 0)) AS "Max_Kickoff_Yards_in_Season",
		MAX(COALESCE(NULLIF(kicking."Touchbacks", ''), 0)) AS "Max_Touchbacks_in_Season",
		MAX(COALESCE(NULLIF(kicking."Touchback_Percent", ''), 0)) AS "Max_Touchback_Percent_in_Season",
		MAX(COALESCE(NULLIF(kicking."Kickoff_Average", ''), 0)) AS "Max_Kickoff_Average_in_Season",
		MAX(COALESCE(NULLIF(kicking."Punts", ''), 0)) AS "Max_Punts_in_Season",
		MAX(COALESCE(NULLIF(kicking."Punt_Yards", ''), 0)) AS "Max_Punt_Yards_in_Season",
		MAX(COALESCE(NULLIF(kicking."Longest_Punt", ''), 0)) AS "Max_Longest_Punt_in_Season",
		MAX(COALESCE(NULLIF(kicking."Punts_Blocked", ''), 0)) AS "Max_Punts_Blocked_in_Season",
		MAX(COALESCE(NULLIF(kicking."Yards_Per_Punt", ''), 0)) AS "Max_Yards_Per_Punt_in_Season",
		0 AS "Max_Standard_Points_in_Season",
		0 AS "Max_PPR_Points_in_Season",
		0 AS "Max_DraftKings_Points_in_Season",
		0 AS "Max_FanDuel_Points_in_Season",
		0 AS "Max_VBD_in_Season",
		MAX(COALESCE(NULLIF(kicking."Rank", ''), 0)) AS "Max_Position_Rank_in_Season",
		MAX(COALESCE(NULLIF(kicking."Rank", ''), 0)) AS "Max_Overall_Rank_in_Season",
		SUM(COALESCE(NULLIF(kicking."Games", ''), 0)) AS "Total_Games",
		SUM(COALESCE(NULLIF(kicking."Starts", ''), 0)) AS "Total_Starts",
		0 AS "Total_Pass_Completions",
		0 AS "Total_Pass_Attempts",
		0 AS "Total_Pass_Yards",
		0 AS "Total_Pass_TDs",
		0 AS "Total_Interceptions",
		0 AS "Total_Rush_Attempts",
		0 AS "Total_Rush_Yards",
		0 AS "Total_Yards_Per_Rush",
		0 AS "Total_Rush_TDs",
		0 AS "Total_Targets",
		0 AS "Total_Receptions",
		0 AS "Total_Receive_Yards",
		0 AS "Total_Yards_Per_Reception",
		0 AS "Total_Receive_TDs",
		0 AS "Total_Fumbles",
		0 AS "Total_Fumbles_Lost",
		0 AS "Total_Total_TDs",
		0 AS "Total_Rush_Conversions",
		0 AS "Total_Pass_Conversions",
		SUM(COALESCE(NULLIF(kicking."0-19_Attempts", ''), 0)) AS "Total_0-19_Attempts",
		SUM(COALESCE(NULLIF(kicking."0-19_Makes", ''), 0)) AS "Total_0-19_Makes",
		SUM(COALESCE(NULLIF(kicking."20-29_Attempts", ''), 0)) AS "Total_20-29_Attempts",
		SUM(COALESCE(NULLIF(kicking."20-29_Makes", ''), 0)) AS "Total_20-29_Makes",
		SUM(COALESCE(NULLIF(kicking."30-39_Attempts", ''), 0)) AS "Total_30-39_Attempts",
		SUM(COALESCE(NULLIF(kicking."30-39_Makes", ''), 0)) AS "Total_30-39_Makes",
		SUM(COALESCE(NULLIF(kicking."40-49_Attempts", ''), 0)) AS "Total_40-49_Attempts",
		SUM(COALESCE(NULLIF(kicking."40-49_Makes", ''), 0)) AS "Total_40-49_Makes",
		SUM(COALESCE(NULLIF(kicking."50+_Attempts", ''), 0)) AS "Total_50+_Attempts",
		SUM(COALESCE(NULLIF(kicking."50+_Makes", ''), 0)) AS "Total_50+_Makes",
		SUM(COALESCE(NULLIF(kicking."FG_Attempts", ''), 0)) AS "Total_FG_Attempts",
		SUM(COALESCE(NULLIF(kicking."FG_Makes", ''), 0)) AS "Total_FG_Makes",
		SUM(COALESCE(NULLIF(kicking."Longest_Make", ''), 0)) AS "Total_Longest_Make",
		SUM(COALESCE(NULLIF(kicking."FG_Percent", ''), 0)) AS "Total_FG_Percent",
		SUM(COALESCE(NULLIF(kicking."XP_Attempts", ''), 0)) AS "Total_XP_Attempts",
		SUM(COALESCE(NULLIF(kicking."XP_Makes", ''), 0)) AS "Total_XP_Makes",
		SUM(COALESCE(NULLIF(kicking."XP_Percent", ''), 0)) AS "Total_XP_Percent",
		SUM(COALESCE(NULLIF(kicking."Kickoffs", ''), 0)) AS "Total_Kickoffs",
		SUM(COALESCE(NULLIF(kicking."Kickoff_Yards", ''), 0)) AS "Total_Kickoff_Yards",
		SUM(COALESCE(NULLIF(kicking."Touchbacks", ''), 0)) AS "Total_Touchbacks",
		SUM(COALESCE(NULLIF(kicking."Touchback_Percent", ''), 0)) AS "Total_Touchback_Percent",
		SUM(COALESCE(NULLIF(kicking."Kickoff_Average", ''), 0)) AS "Total_Kickoff_Average",
		SUM(COALESCE(NULLIF(kicking."Punts", ''), 0)) AS "Total_Punts",
		SUM(COALESCE(NULLIF(kicking."Punt_Yards", ''), 0)) AS "Total_Punt_Yards",
		SUM(COALESCE(NULLIF(kicking."Longest_Punt", ''), 0)) AS "Total_Longest_Punt",
		SUM(COALESCE(NULLIF(kicking."Punts_Blocked", ''), 0)) AS "Total_Punts_Blocked",
		SUM(COALESCE(NULLIF(kicking."Yards_Per_Punt", ''), 0)) AS "Total_Yards_Per_Punt",
		0 AS "Total_Standard_Points",
		0 AS "Total_PPR_Points",
		0 AS "Total_DraftKings_Points",
		0 AS "Total_FanDuel_Points",
		0 AS "Total_VBD"
	FROM (
		SELECT 
			kicking."Player", 
			kicking."Year",
			kicking."Team",
			id_player."Player_Stint_ID", 
			id_player."Player_ID", 
			id_player."Player_Name", 
			dim_team."Coach_Stint_ID", 
			dim_team."Coach_ID", 
			dim_team."Coach_Name", 
			dim_team."Franchise_ID",
			dim_team."Franchise_Name",
			lkp_pos_stint."Primary_Position"
		FROM kicking 
		LEFT JOIN lkp_franchise_abbreviation AS lkp_abrv 
			ON kicking."Team" = lkp_abrv."Abbreviation" 
		LEFT JOIN dim_team 
			ON lkp_abrv."Franchise_Name" = dim_team."Franchise_Name" 
			AND kicking."Year" = dim_team."Year" 
		INNER JOIN lkp_player_name AS lkp_name 
			ON kicking."Player" = lkp_name."Player_Lookup_Name" 
		LEFT JOIN id_player 
			ON lkp_name."Player_Name" = id_player."Player_Name" 
			AND dim_team."Franchise_ID" = id_player."Franchise_ID" 
		LEFT JOIN lkp_primary_position_stint AS lkp_pos_stint 
			ON id_player."Player_Stint_ID" = lkp_pos_stint."Player_Stint_ID"
		GROUP BY 
			kicking."Player", 
			kicking."Year",
			kicking."Team",
			id_player."Player_Stint_ID", 
			id_player."Player_ID", 
			id_player."Player_Name", 
			dim_team."Coach_Stint_ID", 
			dim_team."Coach_ID", 
			dim_team."Coach_Name", 
			dim_team."Franchise_ID",
			dim_team."Franchise_Name",
			lkp_pos_stint."Primary_Position") AS dim_player_stint_sq2
	INNER JOIN kicking 
		ON dim_player_stint_sq2."Player" = kicking."Player" 
		AND dim_player_stint_sq2."Year" = kicking."Year" 
		AND dim_player_stint_sq2."Team" = kicking."Team" 
	WHERE dim_player_stint_sq2."Player_Stint_ID" IS NOT NULL
	GROUP BY 
		dim_player_stint_sq2."Player_Stint_ID", 
		dim_player_stint_sq2."Player_ID", 
		dim_player_stint_sq2."Player_Name", 
		dim_player_stint_sq2."Franchise_ID",
		dim_player_stint_sq2."Franchise_Name",
		dim_player_stint_sq2."Primary_Position";